### ISSUE TITLE
Unknown error code BadDeviceTypeInChallenge

### ISSUE THREAD

**Issue by microshine** [microsoft/Intune-Resource-Access#57]
[ErrorCode](https://github.com/microsoft/Intune-Resource-Access/blob/develop/src/CsrValidation/csharp/ScepValidation/IntuneScepServiceException.cs#L38) doesn't support BadDeviceTypeInChallenge
```
System.Exception: Requested value 'BadDeviceTypeInChallenge' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Microsoft.Intune.IntuneScepServiceException..ctor(String errorCode, String errorDescription, String transactionId, Guid activityId, TraceSource trace) in C:\bitbucket\aeg\src\Intune.ScepValidation\IntuneScepServiceException.cs:line 120
   at Microsoft.Intune.IntuneScepValidator.<PostAsync>d__13.MoveNext() in 
```

**Comment by achuchev** [comment]
@microshine I've faced the same issue when the CSR was coming from Android device. Yesterday, Microsoft confirmed that the issue is now addressed and I can also confirm that it works for me. Maybe, you should try it.
